### ISSUE TITLE
Author name?

### ISSUE THREAD

**Issue by rwbc** [kjljixx/Aurora-Chess-Engine#4]
Hi,

Just in case you want Aurora to be added to the XB/UCI chronology, may I ask if you want to remain anonymous?
(anonymous entries are not possible there)

https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM
(running since 2002)

Guenther (RWBC)

**Comment by kjljixx** [comment]
Hi, it would be great if Aurora could be added. My real name is Winston Cai.

**Comment by rwbc** [comment]
Done! And thanks, Winston :)

Not yet updated in the Details page (will be synchronized tomorrow).
Both google sheet projects are linked from my main page.

https://rwbc-chess.de/

Good luck and fun with the future development of Aurora.

Guenther

**Comment by kjljixx** [comment]
Thank you too!
